apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: django-app
  template:
    metadata:
      labels:
        service: django-app
    spec:
      containers:
       - name: signals
         image: signals-server
         imagePullPolicy: Always
         env:
          - name: POSTGRES_PASSWORD
            value: mysecretpassword
---
apiVersion: v1
kind: Service
metadata:
  name: django-service-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
  - port: 5432
    targetPort: 8000
    nodePort: 30004
